-- merge-clients.sql  (DRY-RUN: ends in ROLLBACK)
-- Single-location: merge the billing anchor INTO its one monitored panel (clean name + number).
-- Multi-location: keep panels, rename the umbrella anchor to '<name> : Billing'.
-- MERGE = re-point FK children then delete the emptied anchor (never a bare delete).
-- APPLY: sed 's/^ROLLBACK;.*/COMMIT;/' server/scripts/merge-clients.sql | sudo -u postgres psql -d phoenix_portal

BEGIN;
SELECT 'BEFORE' phase, count(*) clients FROM clients;

-- ===== single-location merges (survivor = panel id, adopts anchor name+number+billing) =====
UPDATE client_transactions SET client_id=80 WHERE client_id=235;
UPDATE work_orders        SET client_id=80 WHERE client_id=235;
UPDATE dmp_accounts        SET client_id=80 WHERE client_id=235;
UPDATE clients SET name='I-17 Auto and Truck Recycling', customer_id='1076', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=80;
DELETE FROM clients WHERE id=235;
UPDATE client_transactions SET client_id=113 WHERE client_id=394;
UPDATE work_orders        SET client_id=113 WHERE client_id=394;
UPDATE dmp_accounts        SET client_id=113 WHERE client_id=394;
UPDATE clients SET name='Desert Lakes Apts', customer_id='1246', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=113;
DELETE FROM clients WHERE id=394;
UPDATE client_transactions SET client_id=90 WHERE client_id=412;
UPDATE work_orders        SET client_id=90 WHERE client_id=412;
UPDATE dmp_accounts        SET client_id=90 WHERE client_id=412;
UPDATE clients SET name='Cork N Bottle', customer_id='1265', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=90;
DELETE FROM clients WHERE id=412;
UPDATE client_transactions SET client_id=94 WHERE client_id=461;
UPDATE work_orders        SET client_id=94 WHERE client_id=461;
UPDATE dmp_accounts        SET client_id=94 WHERE client_id=461;
UPDATE clients SET name='Sierra Auto Auction', customer_id='1317', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=94;
DELETE FROM clients WHERE id=461;
UPDATE client_transactions SET client_id=15 WHERE client_id=538;
UPDATE work_orders        SET client_id=15 WHERE client_id=538;
UPDATE dmp_accounts        SET client_id=15 WHERE client_id=538;
UPDATE clients SET name='Desert Appeal', customer_id='1399', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=15;
DELETE FROM clients WHERE id=538;
UPDATE client_transactions SET client_id=77 WHERE client_id=602;
UPDATE work_orders        SET client_id=77 WHERE client_id=602;
UPDATE dmp_accounts        SET client_id=77 WHERE client_id=602;
UPDATE clients SET name='Rick Gullette', customer_id='1507', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=77;
DELETE FROM clients WHERE id=602;
UPDATE client_transactions SET client_id=78 WHERE client_id=621;
UPDATE work_orders        SET client_id=78 WHERE client_id=621;
UPDATE dmp_accounts        SET client_id=78 WHERE client_id=621;
UPDATE clients SET name='Buyback Boss', customer_id='1526', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=78;
DELETE FROM clients WHERE id=621;
UPDATE client_transactions SET client_id=82 WHERE client_id=626;
UPDATE work_orders        SET client_id=82 WHERE client_id=626;
UPDATE dmp_accounts        SET client_id=82 WHERE client_id=626;
UPDATE clients SET name='Torah Day School', customer_id='1531', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=82;
DELETE FROM clients WHERE id=626;
UPDATE client_transactions SET client_id=79 WHERE client_id=628;
UPDATE work_orders        SET client_id=79 WHERE client_id=628;
UPDATE dmp_accounts        SET client_id=79 WHERE client_id=628;
UPDATE clients SET name='Ellen Dean', customer_id='1533', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=79;
DELETE FROM clients WHERE id=628;
UPDATE client_transactions SET client_id=84 WHERE client_id=632;
UPDATE work_orders        SET client_id=84 WHERE client_id=632;
UPDATE dmp_accounts        SET client_id=84 WHERE client_id=632;
UPDATE clients SET name='Fairytale Brownies', customer_id='1537', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=84;
DELETE FROM clients WHERE id=632;
UPDATE client_transactions SET client_id=100 WHERE client_id=672;
UPDATE work_orders        SET client_id=100 WHERE client_id=672;
UPDATE dmp_accounts        SET client_id=100 WHERE client_id=672;
UPDATE clients SET name='Arizona Professional Painting', customer_id='1577', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=100;
DELETE FROM clients WHERE id=672;
UPDATE client_transactions SET client_id=101 WHERE client_id=683;
UPDATE work_orders        SET client_id=101 WHERE client_id=683;
UPDATE dmp_accounts        SET client_id=101 WHERE client_id=683;
UPDATE clients SET name='Culvers - Jacob', customer_id='1588', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=101;
DELETE FROM clients WHERE id=683;
UPDATE client_transactions SET client_id=115 WHERE client_id=706;
UPDATE work_orders        SET client_id=115 WHERE client_id=706;
UPDATE dmp_accounts        SET client_id=115 WHERE client_id=706;
UPDATE clients SET name='Compass Christian Church', customer_id='1611', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=115;
DELETE FROM clients WHERE id=706;
UPDATE client_transactions SET client_id=34 WHERE client_id=711;
UPDATE work_orders        SET client_id=34 WHERE client_id=711;
UPDATE dmp_accounts        SET client_id=34 WHERE client_id=711;
UPDATE clients SET name='I Smoke Shea', customer_id='1617', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=34;
DELETE FROM clients WHERE id=711;
UPDATE client_transactions SET client_id=42 WHERE client_id=744;
UPDATE work_orders        SET client_id=42 WHERE client_id=744;
UPDATE dmp_accounts        SET client_id=42 WHERE client_id=744;
UPDATE clients SET name='Jupiter Research', customer_id='1650', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=42;
DELETE FROM clients WHERE id=744;
UPDATE client_transactions SET client_id=18 WHERE client_id=804;
UPDATE work_orders        SET client_id=18 WHERE client_id=804;
UPDATE dmp_accounts        SET client_id=18 WHERE client_id=804;
UPDATE clients SET name='Envoy Data', customer_id='1709', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=18;
DELETE FROM clients WHERE id=804;
UPDATE client_transactions SET client_id=3 WHERE client_id=849;
UPDATE work_orders        SET client_id=3 WHERE client_id=849;
UPDATE dmp_accounts        SET client_id=3 WHERE client_id=849;
UPDATE clients SET name='APD Power Center', customer_id='1755', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=3;
DELETE FROM clients WHERE id=849;
UPDATE client_transactions SET client_id=39 WHERE client_id=856;
UPDATE work_orders        SET client_id=39 WHERE client_id=856;
UPDATE dmp_accounts        SET client_id=39 WHERE client_id=856;
UPDATE clients SET name='Jeep Farm - Alarm', customer_id='1762', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=39;
DELETE FROM clients WHERE id=856;
UPDATE client_transactions SET client_id=57 WHERE client_id=887;
UPDATE work_orders        SET client_id=57 WHERE client_id=887;
UPDATE dmp_accounts        SET client_id=57 WHERE client_id=887;
UPDATE clients SET name='Rayo Whole Sale Phoenix', customer_id='1794', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=57;
DELETE FROM clients WHERE id=887;
UPDATE client_transactions SET client_id=59 WHERE client_id=906;
UPDATE work_orders        SET client_id=59 WHERE client_id=906;
UPDATE dmp_accounts        SET client_id=59 WHERE client_id=906;
UPDATE clients SET name='Sonovision USA Inc', customer_id='1813', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=59;
DELETE FROM clients WHERE id=906;
UPDATE client_transactions SET client_id=58 WHERE client_id=953;
UPDATE work_orders        SET client_id=58 WHERE client_id=953;
UPDATE dmp_accounts        SET client_id=58 WHERE client_id=953;
UPDATE clients SET name='Reconserve of AZ', customer_id='1862', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=58;
DELETE FROM clients WHERE id=953;
UPDATE client_transactions SET client_id=8 WHERE client_id=957;
UPDATE work_orders        SET client_id=8 WHERE client_id=957;
UPDATE dmp_accounts        SET client_id=8 WHERE client_id=957;
UPDATE clients SET name='Blick Art Materials', customer_id='1866', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=8;
DELETE FROM clients WHERE id=957;
UPDATE client_transactions SET client_id=19 WHERE client_id=958;
UPDATE work_orders        SET client_id=19 WHERE client_id=958;
UPDATE dmp_accounts        SET client_id=19 WHERE client_id=958;
UPDATE clients SET name='Event Rents', customer_id='1867', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=19;
DELETE FROM clients WHERE id=958;
UPDATE client_transactions SET client_id=1 WHERE client_id=963;
UPDATE work_orders        SET client_id=1 WHERE client_id=963;
UPDATE dmp_accounts        SET client_id=1 WHERE client_id=963;
UPDATE clients SET name='Achen Construction', customer_id='1872', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=1;
DELETE FROM clients WHERE id=963;
UPDATE client_transactions SET client_id=7 WHERE client_id=966;
UPDATE work_orders        SET client_id=7 WHERE client_id=966;
UPDATE dmp_accounts        SET client_id=7 WHERE client_id=966;
UPDATE clients SET name='Biltmore ENT', customer_id='1875', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=7;
DELETE FROM clients WHERE id=966;
UPDATE client_transactions SET client_id=2 WHERE client_id=979;
UPDATE work_orders        SET client_id=2 WHERE client_id=979;
UPDATE dmp_accounts        SET client_id=2 WHERE client_id=979;
UPDATE clients SET name='Alliance Plumbing', customer_id='1888', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=2;
DELETE FROM clients WHERE id=979;
UPDATE client_transactions SET client_id=17 WHERE client_id=988;
UPDATE work_orders        SET client_id=17 WHERE client_id=988;
UPDATE dmp_accounts        SET client_id=17 WHERE client_id=988;
UPDATE clients SET name='Drinique', customer_id='1897', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=17;
DELETE FROM clients WHERE id=988;
UPDATE client_transactions SET client_id=31 WHERE client_id=990;
UPDATE work_orders        SET client_id=31 WHERE client_id=990;
UPDATE dmp_accounts        SET client_id=31 WHERE client_id=990;
UPDATE clients SET name='Hellas Construction', customer_id='1899', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=31;
DELETE FROM clients WHERE id=990;
UPDATE client_transactions SET client_id=13 WHERE client_id=1000;
UPDATE work_orders        SET client_id=13 WHERE client_id=1000;
UPDATE dmp_accounts        SET client_id=13 WHERE client_id=1000;
UPDATE clients SET name='Damien Clark', customer_id='1909', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=13;
DELETE FROM clients WHERE id=1000;
UPDATE client_transactions SET client_id=69 WHERE client_id=1021;
UPDATE work_orders        SET client_id=69 WHERE client_id=1021;
UPDATE dmp_accounts        SET client_id=69 WHERE client_id=1021;
UPDATE clients SET name='Trek Bicycle', customer_id='1930', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=69;
DELETE FROM clients WHERE id=1021;
UPDATE client_transactions SET client_id=12 WHERE client_id=1044;
UPDATE work_orders        SET client_id=12 WHERE client_id=1044;
UPDATE dmp_accounts        SET client_id=12 WHERE client_id=1044;
UPDATE clients SET name='Cunningham Law', customer_id='1953', billing_amount=COALESCE(NULLIF(billing_amount,0),0) WHERE id=12;
DELETE FROM clients WHERE id=1044;

-- ===== multi-location umbrellas: rename to '<name> : Billing' =====
UPDATE clients SET name=name||' : Billing' WHERE id=178 AND name NOT LIKE '% : Billing';
UPDATE clients SET name=name||' : Billing' WHERE id=271 AND name NOT LIKE '% : Billing';
UPDATE clients SET name=name||' : Billing' WHERE id=369 AND name NOT LIKE '% : Billing';
UPDATE clients SET name=name||' : Billing' WHERE id=435 AND name NOT LIKE '% : Billing';
UPDATE clients SET name=name||' : Billing' WHERE id=464 AND name NOT LIKE '% : Billing';
UPDATE clients SET name=name||' : Billing' WHERE id=546 AND name NOT LIKE '% : Billing';
UPDATE clients SET name=name||' : Billing' WHERE id=559 AND name NOT LIKE '% : Billing';
UPDATE clients SET name=name||' : Billing' WHERE id=591 AND name NOT LIKE '% : Billing';
UPDATE clients SET name=name||' : Billing' WHERE id=595 AND name NOT LIKE '% : Billing';
UPDATE clients SET name=name||' : Billing' WHERE id=668 AND name NOT LIKE '% : Billing';
UPDATE clients SET name=name||' : Billing' WHERE id=732 AND name NOT LIKE '% : Billing';
UPDATE clients SET name=name||' : Billing' WHERE id=787 AND name NOT LIKE '% : Billing';
UPDATE clients SET name=name||' : Billing' WHERE id=917 AND name NOT LIKE '% : Billing';
UPDATE clients SET name=name||' : Billing' WHERE id=972 AND name NOT LIKE '% : Billing';
UPDATE clients SET name=name||' : Billing' WHERE id=985 AND name NOT LIKE '% : Billing';
UPDATE clients SET name=name||' : Billing' WHERE id=1030 AND name NOT LIKE '% : Billing';

-- ===== create billing umbrellas for multi-panel customers whose anchor was deleted junk =====
INSERT INTO clients (customer_id, name, customer_number, monitoring_enabled, services, created_at) VALUES ('716','JF Long Properties : Billing','716', false, '{}', now());
INSERT INTO clients (customer_id, name, customer_number, monitoring_enabled, services, created_at) VALUES ('1940','Elontec : Billing','1940', false, '{}', now());
INSERT INTO clients (customer_id, name, customer_number, monitoring_enabled, services, created_at) VALUES ('1948','FLW Storage LLC : Billing','1948', false, '{}', now());

-- ===== verification =====
SELECT 'AFTER' phase, count(*) clients, count(*) FILTER (WHERE monitoring_enabled) monitored, count(DISTINCT customer_number) distinct_customers FROM clients;
SELECT 'transactions' k, count(*) FROM client_transactions;
SELECT customer_number, count(*) rows_for_customer FROM clients WHERE customer_number IS NOT NULL GROUP BY customer_number HAVING count(*)>1 ORDER BY 2 DESC;

ROLLBACK;  -- flip to COMMIT to apply
